### ISSUE TITLE
大佬米游币要不要跟进一下

### ISSUE THREAD

**Issue by z13202013** [yinghualuowu/GenshinDailyHelper#1]
米游币被抽奖回收了,错失60原石。现在更懒得点了
[米游币](https://github.com/jianggaocheng/mihoyo-signin)

**Comment by z13202013** [comment]
当我没说,米游社每日签到又改了

**Comment by yinghualuowu** [comment]
接口有变动，需要时间修复。这些天只能手动签到啦~~

**Comment by yinghualuowu** [comment]
现在可以正常签到了（至少不会报错）
