### ISSUE TITLE
虽说比较严格

### ISSUE THREAD

**Issue by aierlma** [yinghualuowu/GenshinDailyHelper#11]
>Additionally, Actions should not be used for: any activity that places a burden on our servers, where that burden is disproportionate to the benefits provided to users (for example, don't use Actions as a content delivery network or as part of a serverless application, but a low benefit Action could be ok if it’s also low burden)

引用自[https://docs.github.com/en/github/site-policy/github-terms-for-additional-products-and-features](https://docs.github.com/en/github/site-policy/github-terms-for-additional-products-and-features)
这个小东西还是ok的，当然如果实在不放心还是不用也行

**Comment by yinghualuowu** [comment]
如果fork量大了就有问题，python版的就这样没的。最近太忙了，没办法做腾讯云的。咕咕咕咕
