### ISSUE TITLE
我能把这个项目加入到刻记牛杂店吗？

### ISSUE THREAD

**Issue by Scighost** [yinghualuowu/GenshinDailyHelper#12]
您好，我能把这个项目加入到[刻记牛杂店](https://github.com/Scighost/KeqingNiuza)吗？
（虽然都是MIT许可，我还是觉得先询问一下比较好）

**Comment by yinghualuowu** [comment]
可以~~~~

**Comment by Scighost** [comment]
感谢 (｡･ω･｡)ﾉ♡

**Comment by Lightczx** [comment]
我已经嵌入我我的项目里了，可以参考一下
https://github.com/DGP-Studio/Snap.Genshin/blob/main/DGP.Genshin/Services/DailySignInService.cs

**Comment by Lightczx** [comment]
一旦取得了Cookie实际上就可以获取用户的头像与昵称等信息了
https://github.com/DGP-Studio/Snap.Genshin/blob/main/DGP.Genshin/Services/MiHoYoBBSService.cs

**Comment by Scighost** [comment]
> 我已经嵌入到我的项目里了，可以参考一下
> https://github.com/DGP-Studio/Snap.Genshin/blob/main/DGP.Genshin/Services/DailySignInService.cs

我没有自己写，直接照搬了本项目，在系统里加一个任务计划就可以实现自动签到了，当然没有Actions或云函数好用

**Comment by Scighost** [comment]
> 一旦取得了Cookie实际上就可以获取用户的头像与昵称等信息了
> https://github.com/DGP-Studio/Snap.Genshin/blob/main/DGP.Genshin/Services/MiHoYoBBSService.cs

计划在下一个项目中加入展示米游社信息的功能，牛杂店代码太乱不想改了

**Comment by Lightczx** [comment]
hhhhh太乱是真的
我看的时候一愣一愣的
