### ISSUE TITLE
获取参数不对

### ISSUE THREAD

**Issue by Skr-Skr** [yinghualuowu/GenshinDailyHelper#5]
![image](https://user-images.githubusercontent.com/44292122/115338863-47867700-a1d6-11eb-9c93-5f19fe7ea2ca.png)

另外想问一下，咱这个会不会封号

**Comment by yinghualuowu** [comment]
传递进来的cookie信息应该不对。
其实有个超级大的项目不知道怎么跑路了，我其实挺慌的（

**Comment by Skr-Skr** [comment]
> 传递进来的cookie信息应该不对。
> 其实有个超级大的项目不知道怎么跑路了，我其实挺慌的（

谢谢，的确是cookie信息设置的不对。不过听你这么一说我又不敢用了（
