### ISSUE TITLE
关于DS生成有一些不懂得地方求解答

### ISSUE THREAD

**Issue by DrMuda** [yinghualuowu/GenshinDailyHelper#7]
**1.** 我用[md5生成网站](https://www.sojson.com/encrypt_md5.html)试着将AppVersion加密，但是得到的和代码里写的Salt并不一致，以及为何这里不直接通过AppVersion这个变量生成呢
    预期：md5加密“2.3.0”， 得到代码里的Salt值h8w582wxwgqvahcdkpvdhbh2w9casgfl
    实际：md5加密“2.3.0”，得到70e2b24f7d348efe6b30b41469d5070c
![image](https://user-images.githubusercontent.com/73845204/116494041-96b56180-a8d2-11eb-93c1-2348751f20d7.png)

**2.** 同样的，我通过抓包工具获得了
    版本号: 2.7.0
    DS: 1619662287,h8c32p,8661504445ea02db9cd34e0e29559663
    我将版本号通过上面所说的网站加密得到salt: b1d71238024fc4efb8359ec8404be1a0，然后按照代码拼接stringAdd得到salt=b1d71238024fc4efb8359ec8404be1a0&t=1619662287&r=h8c32p, 再加密这个字符串，得到的是: 2f13fdec487ad9616a5296d8a625a7b2， 与DS的第三部分也不一致; 
我并没有学过c#语言，这个字符串拼接的方式是百度得来的，不知道我是否搞错了，以及因为不懂，所以我没能在本地把项目跑起来，做常规的测试

**Comment by 1941260986** [comment]
> **1.** 我用[md5生成网站](https://www.sojson.com/encrypt_md5.html)试着将AppVersion加密，但是得到的和代码里写的Salt并不一致，以及为何这里不直接通过AppVersion这个变量生成呢
> 预期：md5加密“2.3.0”， 得到代码里的Salt值h8w582wxwgqvahcdkpvdhbh2w9casgfl
> 实际：md5加密“2.3.0”，得到70e2b24f7d348efe6b30b41469d5070c
> ![image](https://user-images.githubusercontent.com/73845204/116494041-96b56180-a8d2-11eb-93c1-2348751f20d7.png)
> 
> **2.** 同样的，我通过抓包工具获得了
> 版本号: 2.7.0
> DS: 1619662287,h8c32p,8661504445ea02db9cd34e0e29559663
> 我将版本号通过上面所说的网站加密得到salt: b1d71238024fc4efb8359ec8404be1a0，然后按照代码拼接stringAdd得到salt=b1d71238024fc4efb8359ec8404be1a0&t=1619662287&r=h8c32p, 再加密这个字符串，得到的是: 2f13fdec487ad9616a5296d8a625a7b2， 与DS的第三部分也不一致;
> 我并没有学过c#语言，这个字符串拼接的方式是百度得来的，不知道我是否搞错了，以及因为不懂，所以我没能在本地把项目跑起来，做常规的测试

你们是如何抓包的，我用fiddler抓包米游社，一打开app米游社就请求失败，打开其他app却是正常运行，能看到请求响应

**Comment by yinghualuowu** [comment]
从2021.1.1开始，salt已经不再是通过版本号得到，而是通过逆向js才得到了。具体的逆向流程因为上一个项目的404而丢失

**Comment by DrMuda** [comment]
> > **1.** 我用[md5生成网站](https://www.sojson.com/encrypt_md5.html)试着将AppVersion加密，但是得到的和代码里写的Salt并不一致，以及为何这里不直接通过AppVersion这个变量生成呢
> > 预期：md5加密“2.3.0”， 得到代码里的Salt值h8w582wxwgqvahcdkpvdhbh2w9casgfl
> > 实际：md5加密“2.3.0”，得到70e2b24f7d348efe6b30b41469d5070c
> > ![image](https://user-images.githubusercontent.com/73845204/116494041-96b56180-a8d2-11eb-93c1-2348751f20d7.png)
> > **2.** 同样的，我通过抓包工具获得了
> > 版本号: 2.7.0
> > DS: 1619662287,h8c32p,8661504445ea02db9cd34e0e29559663
> > 我将版本号通过上面所说的网站加密得到salt: b1d71238024fc4efb8359ec8404be1a0，然后按照代码拼接stringAdd得到salt=b1d71238024fc4efb8359ec8404be1a0&t=1619662287&r=h8c32p, 再加密这个字符串，得到的是: 2f13fdec487ad9616a5296d8a625a7b2， 与DS的第三部分也不一致;
> > 我并没有学过c#语言，这个字符串拼接的方式是百度得来的，不知道我是否搞错了，以及因为不懂，所以我没能在本地把项目跑起来，做常规的测试
> 
> 你们是如何抓包的，我用fiddler抓包米游社，一打开app米游社就请求失败，打开其他app却是正常运行，能看到请求响应

我是用手机上的一个软件HttpCanary（小黄鸟），请求失败有可能是因为证书问题，软件官网上有关于这个问题的解决方法

**Comment by DrMuda** [comment]
> 从2021.1.1开始，salt已经不再是通过版本号得到，而是通过逆向js才得到了。具体的逆向流程因为上一个项目的404而丢失

了解了
